language:               ""
title:                  "Pavement Preservation"
description:            "Resource for Practicing Professionals"
google-verification:    ""

# source:      .
# destination: ./_site
# plugins:     ./_plugins
# layouts:     ./_layouts
include:      [
                '.htaccess',
                '.nojekyll'
              ]

# exclude from the conversion and from sitemap.xml
exclude:      [
                'node_modules',
                'npm-debug.log',
                'package.json',
                'bower.json',
                'gulpfile.js',
                'Makefile',
                'composer.json',
                'composer.lock',
                'README.md',
                'Gemfile',
                'Gemfile.lock',
                'assets/vendor/foundation-icon-fonts/*.html',
                'assets/vendor/phpmailer/**/*.html',
                'assets/vendor/what-input/*.html',
                'assets/vendor/*.scss',
                'assets/scss/*.scss',
                'assets/js/app.js',
                'assets/js/all.js',
                'Rakefile'
              ]
# keep_files:  ['.git','.svn']
plugins:
 - jekyll-sitemap
 - jekyll-paginate

timezone: America/New_York
# encoding:    nil

# future:      true
# show_drafts: false
# limit_posts: 0
# highlighter: pygments

paginate_path: '/news/page:num'
paginate:      5

# markdown:      kramdown
# markdown_ext:  markdown,mkdown,mkdn,mkd,md
# textile_ext:   textile

excerpt_separator: "<!--more-->"

# safe:        false
# watch:       false    # deprecated
# server:      false    # deprecated
# host:        0.0.0.0
# port:        4000
# url:         ""
baseurl:     "/p2"
# lsi:         false

# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex
#   fenced_code_blocks: true

# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: false
    parse_block_html: true
    parse_span_html: true
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# redcloth:
#   hard_breaks: true

permalink: pretty

############### GITHUB ####################
# Used by Rakefile to push code and generated pages to github pages
github:
  user:       "captaincoffee" # eg: toto
  repository: "p2"   # eg: project-repo or p2.github.io
  remoteName: "origin"
  branches:
    -
     name: "master"
     path: ""
    -
     name: "gh-pages" # or *master* for user/organisation repository. eg: p2.github.io
     path: "_site"

############### RELATED ARTICLES ####################
# if set to true print a list of related articles
# on collection's articles
printRelatedArticles: true

# maximum number of related articles searched in each collection
maxRelated : 4
# minimum number of tag match to be a related
minTagMatch: 4
############### COLLECTIONS ####################
collections:

  methods:
    output: true   # every page in the collection will be created
    isKB: true     # is part of Knowledge base
    name: "Methods" # Print name used in titles, menus, ...
    categories:
      - { name: "Fog, Tack & Spray Seals", slug: "fog-tack-and-spray-seals" }
      - { name: "Chip Seals", slug: "chip-seals" }
      - { name: "Microsurfacing, Slurry & Cape Seals", slug: "microsurfacing-slurry-and-cape-seals" }
      - { name: "Cold-Mix Asphalt", slug: "cold-mix-asphalt" }
      - { name: "Hot and Warm-Mix Asphalt", slug: "hot-and-warm-mix-asphalt" }
      - { name: "Central Plant Recycling - Plant", slug: "central-plant-recycling" }
      - { name: "In-Place Recycling", slug: "in-place-recycling" }
      - { name: "Crack & Joint Treatments", slug: "crack-joint-treatments" }
      - { name: "Pothole Patching & Preparation", slug: "pothole-patching-preparation" }
      - { name: "Milling & Grinding", slug: "milling-and-grinding" }
      - { name: "Concrete Overlays", slug: "concrete-overlays" }

  materials:
    output: true
    isKB: true
    name: Materials
    categories:
      - { name: "Aggregates", slug: "aggregates" }
      - { name: "Asphalt Emulsions", slug: "asphalt-emulsions" }
      - { name: "Rejuvenators and Recycling Agents", slug: "rejuvenators-and-recycling-agents" }
      - { name: "Asphalt Binders", slug: "asphalt-binders" }
      - { name: "Asphalt Additives & Modifiers", slug: "asphalt-additives-and-modifiers" }
      - { name: "Mixture Additives & Modifiers", slug: "mixture-additives-and-modifiers" }
      - { name: "RAP", slug: "rap" }
      - { name: "RAS, GTR, & Recycled Materials", slug: "ras-gtr-recycled-materials" }
      - { name: "Concrete", slug: "concrete" }

  manage:
    output: true
    isKB: true
    name: Manage
    categories:
      - { name: "Safety", slug: "safety" }
      - { name: "Strategy", slug: "strategy" }
      - { name: "Pavement Management Systems", slug: "pavement-management-systems" }
      - { name: "Specifications & Tests", slug: "specifications-and-tests" }
      - { name: "Quality Control & Assurance", slug: "quality-control-assurance" }
      - { name: "Quick Links", slug: "quick-links" }
      - { name: "Research", slug: "research" }
      - { name: "Life Cycle Cost Analysis", slug: "life-cycle-cost-analysis" }
      - { name: "Data Management", slug: "data-management" }
      - { name: "Training", slug: "training" }

############### ARTICLES TYPES ####################
# this array determine article's types and order
# a collection article with non matching type will not be listed
# article must be tagged with a type.slug
# eg : "type: article" or "type: research"

articleTypes :
  - { name: "Article", plural: "Articles", slug: "article", icon: "fi-page" }
  - { name: "Video", plural: "Videos", slug: "video", icon: "fi-video" }
  - { name: "Link", plural: "Links", slug: "link", icon: "fi-link" }
  - { name: "Project", plural: "Projects", slug: "project", icon: "fi-page-search" }
  - { name: "Research", plural: "Research", slug: "research", icon: "fi-compass" }

############### DEFAULT CONFIGURATION ####################
defaults:

  - { scope: { type: "posts" }, values: { permalink: "/news/:year/:title/", layout: "post"} }

  - { scope: { type: "pages" }, values: { layout: "default" } }

  # default layout for collections articles
  - { scope: { type: "methods" }, values: { layout: "collection" } }
  - { scope: { type: "materials" }, values: { layout: "collection" } }
  - { scope: { type: "management" }, values: { layout: "collection" } }

  # assign a default category to any item in a given folder
  - { scope: { path: "_methods/fog-tack-and-spray-seals" }, values:  { category: "fog-tack-and-spray-seals" } }
  - { scope: { path: "_methods/chip-seals" }, values:  { category: "chip-seals" } }
  - { scope: { path: "_methods/microsurfacing-slurry-and-cape-seals" }, values:  { category: "microsurfacing-slurry-and-cape-seals" } }
  - { scope: { path: "_methods/cold-mix-asphalt" }, values:  { category: "cold-mix-asphalt" } }
  - { scope: { path: "_methods/hot-and-warm-mix-asphalt" }, values:  { category: "hot-and-warm-mix-asphalt" } }
  - { scope: { path: "_methods/central-plant-recycling" }, values:  { category: "central-plant-recycling" } }
  - { scope: { path: "_methods/in-place-recycling" }, values:  { category: "in-place-recycling" } }
  - { scope: { path: "_methods/crack-joint-treatments" }, values:  { category: "crack-joint-treatments" } }
  - { scope: { path: "_methods/concrete-overlays" }, values:  { category: "concrete-overlays" } }
  - { scope: { path: "_methods/pothole-patching-preparation" }, values:  { category: "pothole-patching-preparation" } }
  - { scope: { path: "_methods/milling-and-grinding" }, values:  { category: "milling-and-grinding" } }

  - { scope: { path: "_materials/aggregates" }, values:  { category: "aggregates" } }
  - { scope: { path: "_materials/asphalt-emulsions" }, values:  { category: "asphalt-emulsions" } }
  - { scope: { path: "_materials/rejuvenators-and-recycling-agents" }, values:  { category: "rejuvenators-and-recycling-agents" } }
  - { scope: { path: "_materials/asphalt-binders" }, values:  { category: "asphalt-binders" } }
  - { scope: { path: "_materials/asphalt-additives-and-modifiers" }, values:  { category: "asphalt-additives-and-modifiers" } }
  - { scope: { path: "_materials/mixture-additives-and-modifiers" }, values:  { category: "mixture-additives-and-modifiers" } }
  - { scope: { path: "_materials/rap" }, values:  { category: "rap" } }
  - { scope: { path: "_materials/ras-gtr-recycled-materials" }, values:  { category: "ras-gtr-recycled-materials" } }
  - { scope: { path: "_materials/concrete" }, values:  { category: "concrete" } }

  - { scope: { path: "_manage/safety" }, values:  { category: "safety" } }
  - { scope: { path: "_manage/quick-links" }, values:  { category: "quick-links" } }
  - { scope: { path: "_manage/strategy" }, values:  { category: "strategy" } }
  - { scope: { path: "_manage/pavement-management-systems" }, values:  { category: "pavement-management-systems" } }
  - { scope: { path: "_manage/specifications-and-tests" }, values:  { category: "specifications-and-tests" } }
  - { scope: { path: "_manage/quality-control-assurance" }, values:  { category: "quality-control-assurance" } }
  - { scope: { path: "_manage/research" }, values:  { category: "research" } }
  - { scope: { path: "_manage/life-cycle-cost-analysis" }, values:  { category: "life-cycle-cost-analysis" } }
  - { scope: { path: "_manage/data-management" }, values:  { category: "data-management" } }
  - { scope: { path: "_manage/training" }, values:  { category: "training" } }
